### ISSUE TITLE
Global install

### ISSUE THREAD

**Issue by sindresorhus** [pwmckenna/generator-travis-ci#1]
Generators can now be installed globally. Please update the readme:

`npm install -g generator-travis-ci`

**Comment by pwmckenna** [comment]
awesome!

**Comment by pwmckenna** [comment]
Updated readme, as well as adding the package.json recommendation to install globally.

https://github.com/pwmckenna/generator-travis-ci/commit/a6fd7e78a48bed75d3bc447d6f7bc16795c463f2
