### ISSUE TITLE
Option to push dist into other named repo.

### ISSUE THREAD

**Issue by mysterycommand** [pwmckenna/generator-travis-ci#2]
It would be great if there was a way to have this pull from the default branch and then push into an arbitrarily named branch. This way the generator could also work for GitHub User and Organization Pages by pulling from branch develop, and pushing dist into branch master.

Maybe rename the gh-pages generator simply pages, and add an option to specify the branch to push into? Something like:

`yo travis-ci:pages --branch gh-pages`
`yo travis-ci:pages --branch master`

… or, since those are the only two likely use cases, maybe something like:

`yo travis-ci:pages-project`
`yo travis-ci:pages-userorg`

Do you see any problems with this?

**Comment by pwmckenna** [comment]
This is a great idea! Given that the generator already collects enough information to know when its being used on a user/org page, I'll just need to add a single question in those cases asking what branch to build from. I'll keep this open until I implement... Hopefully by the end of the week.

**Comment by pwmckenna** [comment]
Added support for user&organization pages here: https://github.com/pwmckenna/generator-travis-ci/commit/14aef6874782deb02d5c0dc3dad72117ae4a06ad

@mysterycommand mind taking a look and telling me what you think? This feature is available in the latest npm version (0.6.0)

**Comment by mysterycommand** [comment]
Thanks for the update Patrick … it worked like a charm except for one thing: in `TravisGenerator.prototype.insertReadmeStatusImage` ([/lib/travis-generator.js#L328](https://github.com/pwmckenna/generator-travis-ci/blob/14aef6874782deb02d5c0dc3dad72117ae4a06ad/lib/travis-generator.js#L328)) `?branch=master` should probably be `?branch=<%= sourceBranch %>` for the user/org pages case.
