### ISSUE TITLE
Add  "[ci skip]" to Commit Message

### ISSUE THREAD

**Issue by mysterycommand** [pwmckenna/generator-travis-ci#4]
I just realized that with the new user/org configuration, Travis CI gets triggered every time it automatically pushes into `master`, and since `master` is the deployed site, there's no `.travis.yml` to there to tell it not to re-run the build (and probably fail).

Rather than copy a (somewhat extraneous) `.travis.yml` file around in  the `app/` and `dist/` directories, I think you could just add `[ci skip]` to the commit message that deploys the built files. References (note in the first link that the `gh-pages` link is by default blacklisted, unless you whitelist it):

http://about.travis-ci.org/docs/user/build-configuration/#.travis.yml-and-multiple-branches
http://about.travis-ci.org/docs/user/how-to-skip-a-build/

**Comment by pwmckenna** [comment]
definitely a good call. I'll add this and bump the minor version. I added you as a contributor, so if you feel like getting your hands dirty, feel free.

**Comment by pwmckenna** [comment]
done: ed72520ddfc7960bc91f2ec08bad9842cbc104de

published in version 0.6.1
